use crate::{game::Tile, template::{BoardTemplate, FieldTemplate, HomeTemplate}};

use super::Position;

pub const NORMAL: BoardTemplate<46, 30, 7> = BoardTemplate {
    fields: [
        FieldTemplate { position: Position(-4, 3), tile: Tile::Mountain, tunnelable: false, explorer_token: false },
        FieldTemplate { position: Position(-3, 3), tile: Tile::Farm, tunnelable: false, explorer_token: false },
        FieldTemplate { position: Position(-2, 3), tile: Tile::Village, tunnelable: false, explorer_token: true },
        FieldTemplate { position: Position(-1, 3), tile: Tile::Woods, tunnelable: false, explorer_token: false },
        FieldTemplate { position: Position(0, 3), tile: Tile::Tundra, tunnelable: false, explorer_token: false },
        FieldTemplate { position: Position(1, 3), tile: Tile::Village, tunnelable: false, explorer_token: false },

        FieldTemplate { position: Position(-4, 2), tile: Tile::Lake, tunnelable: false, explorer_token: false },
        FieldTemplate { position: Position(-3, 2), tile: Tile::Tundra, tunnelable: false, explorer_token: true },
        FieldTemplate { position: Position(-2, 2), tile: Tile::Lake, tunnelable: false, explorer_token: false },
        FieldTemplate { position: Position(-1, 2), tile: Tile::Tundra, tunnelable: true, explorer_token: false },
        FieldTemplate { position: Position(0, 2), tile: Tile::Mountain, tunnelable: false, explorer_token: true },
        FieldTemplate { position: Position(1, 2), tile: Tile::Farm, tunnelable: false, explorer_token: false },
        FieldTemplate { position: Position(2, 2), tile: Tile::Farm, tunnelable: false, explorer_token: true },
        
        FieldTemplate { position: Position(-3, 1), tile: Tile::Woods, tunnelable: false, explorer_token: false },
        FieldTemplate { position: Position(-2, 1), tile: Tile::Mountain, tunnelable: true, explorer_token: false },
        FieldTemplate { position: Position(-1, 1), tile: Tile::Woods, tunnelable: false, explorer_token: false },
        FieldTemplate { position: Position(0, 1), tile: Tile::Lake, tunnelable: false, explorer_token: false },
        FieldTemplate { position: Position(1, 1), tile: Tile::Woods, tunnelable: true, explorer_token: false },
        FieldTemplate { position: Position(2, 1), tile: Tile::Village, tunnelable: false, explorer_token: false },
        
        FieldTemplate { position: Position(-3, 0), tile: Tile::Farm, tunnelable: false, explorer_token: false },
        FieldTemplate { position: Position(-2, 0), tile: Tile::Village, tunnelable: false, explorer_token: true },
        FieldTemplate { position: Position(-1, 0), tile: Tile::Lake, tunnelable: false, explorer_token: false },
        FieldTemplate { position: Position(0, 0), tile: Tile::Factory, tunnelable: false, explorer_token: false },
        FieldTemplate { position: Position(1, 0), tile: Tile::Mountain, tunnelable: false, explorer_token: false },
        FieldTemplate { position: Position(2, 0), tile: Tile::Tundra, tunnelable: false, explorer_token: true },
        FieldTemplate { position: Position(3, 0), tile: Tile::Mountain, tunnelable: false, explorer_token: false },
        
        FieldTemplate { position: Position(-3, -1), tile: Tile::Woods, tunnelable: false, explorer_token: true },
        FieldTemplate { position: Position(-2, -1), tile: Tile::Woods, tunnelable: false, explorer_token: false },
        FieldTemplate { position: Position(-1, -1), tile: Tile::Farm, tunnelable: true, explorer_token: false },
        FieldTemplate { position: Position(0, -1), tile: Tile::Tundra, tunnelable: false, explorer_token: false },
        FieldTemplate { position: Position(1, -1), tile: Tile::Lake, tunnelable: false, explorer_token: false },
        FieldTemplate { position: Position(2, -1), tile: Tile::Village, tunnelable: true, explorer_token: false },
        FieldTemplate { position: Position(3, -1), tile: Tile::Lake, tunnelable: false, explorer_token: false },
        
        FieldTemplate { position: Position(-2, -2), tile: Tile::Mountain, tunnelable: false, explorer_token: false },
        FieldTemplate { position: Position(-1, -2), tile: Tile::Village, tunnelable: false, explorer_token: true },
        FieldTemplate { position: Position(0, -2), tile: Tile::Village, tunnelable: false, explorer_token: true },
        FieldTemplate { position: Position(1, -2), tile: Tile::Tundra, tunnelable: true, explorer_token: false },
        FieldTemplate { position: Position(2, -2), tile: Tile::Woods, tunnelable: false, explorer_token: false },
        FieldTemplate { position: Position(3, -2), tile: Tile::Mountain, tunnelable: false, explorer_token: true },
        FieldTemplate { position: Position(4, -2), tile: Tile::Tundra, tunnelable: false, explorer_token: false },
        
        FieldTemplate { position: Position(0, -3), tile: Tile::Lake, tunnelable: false, explorer_token: false },
        FieldTemplate { position: Position(1, -3), tile: Tile::Farm, tunnelable: false, explorer_token: false },
        FieldTemplate { position: Position(2, -3), tile: Tile::Mountain, tunnelable: false, explorer_token: true },
        FieldTemplate { position: Position(3, -3), tile: Tile::Village, tunnelable: false, explorer_token: false },
        FieldTemplate { position: Position(4, -3), tile: Tile::Farm, tunnelable: false, explorer_token: false },
        
        FieldTemplate { position: Position(2, -4), tile: Tile::Village, tunnelable: false, explorer_token: false },
    ],
    rivers: [
        (Position(-2,3),Position(-1,3)),
        (Position(0,3),Position(1,3)),
        (Position(-2,3),Position(-1,2)),
        (Position(-1,3),Position(-1,2)),
        (Position(0,3),Position(1,2)),
        (Position(-1,2),Position(0,2)),
        (Position(0,2),Position(1,2)),
        (Position(-3,2),Position(-3,1)),
        (Position(0,2),Position(1,1)),
        (Position(1,2),Position(2,1)),
        (Position(-3,1),Position(-2,1)),
        (Position(1,1),Position(2,1)),
        (Position(-2,0),Position(-2,1)),
        (Position(1,1),Position(2,0)),
        (Position(1,0),Position(2,0)),
        (Position(-3,-1),Position(-3,0)),
        (Position(-3,0),Position(-2,-1)),
        (Position(-2,-1),Position(-2,0)),
        (Position(-2,0),Position(-1,-1)),
        (Position(2,0),Position(3,-1)),
        (Position(-3,-1),Position(-2,-2)),
        (Position(-2,-2),Position(-2,-1)),
        (Position(-2,1),Position(-1,-2)),
        (Position(-1,-2),Position(-1,-1)),
        (Position(-1,-2),Position(0,-2)),
        (Position(0,-2),Position(1,-3)),
        (Position(1,-3),Position(1,-2)),
        (Position(1,-2),Position(2,-3)),
        (Position(2,-3),Position(2,-2)),
        (Position(2,-3),Position(3,-3)),
    ],
    starting_locations: [
        HomeTemplate{position: Position(3,1), start1: Position(2,1), start2: Position(3,0) },
        HomeTemplate{position: Position(-1,4), start1: Position(-1,3), start2: Position(0,3) },
        HomeTemplate{position: Position(-4,4), start1: Position(-4,3), start2: Position(-3,3) },
        HomeTemplate{position: Position(-4,1), start1: Position(-3,1), start2: Position(-3,0) },
        HomeTemplate{position: Position(-2,-3), start1: Position(-2,-2), start2: Position(-1,-3) },
        HomeTemplate{position: Position(1,-4), start1: Position(1,-3), start2: Position(2,-4) },
        HomeTemplate{position: Position(5,-3), start1: Position(4,-3), start2: Position(4,-2) },
    ],
};
