use super::PlayerMat;
use super::SecondaryAction;

pub const INDUSTRIAL: PlayerMat = PlayerMat {
    name: "Industrial",
    starting_index: 1,
    starting_coins: 4,
    starting_popularity: 2,
    move_secondary: SecondaryAction::Build,
    trade_secondary: SecondaryAction::Enlist,
    produce_secondary: SecondaryAction::Deploy,
    bolster_secondary: SecondaryAction::Upgrade,
    upgrade_cost: 2,
    upgrade_evolutions: 1,
    upgrade_coins: 3,
    deploy_cost: 1,
    deploy_evolutions: 2,
    deploy_coins: 2,
    build_cost: 2,
    build_evolutions: 1,
    build_coins: 1,
    enlist_cost: 2,
    enlist_evolutions: 2,
    enlist_coins: 0,
};

pub const ENGINEERING: PlayerMat = PlayerMat {
    name: "Engineering",
    starting_index: 2,
    starting_coins: 5,
    starting_popularity: 2,
    move_secondary: SecondaryAction::Enlist,
    trade_secondary: SecondaryAction::Deploy,
    produce_secondary: SecondaryAction::Upgrade,
    bolster_secondary: SecondaryAction::Build,
    upgrade_cost: 2,
    upgrade_evolutions: 1,
    upgrade_coins: 2,
    deploy_cost: 2,
    deploy_evolutions: 2,
    deploy_coins: 0,
    build_cost: 1,
    build_evolutions: 2,
    build_coins: 3,
    enlist_cost: 2,
    enlist_evolutions: 1,
    enlist_coins: 1,
};


pub const PATRIOTIC: PlayerMat = PlayerMat {
    name: "Patriotic",
    starting_index: 3,
    starting_coins: 6,
    starting_popularity: 2,
    move_secondary: SecondaryAction::Upgrade,
    trade_secondary: SecondaryAction::Build,
    produce_secondary: SecondaryAction::Enlist,
    bolster_secondary: SecondaryAction::Deploy,
    upgrade_cost: 2,
    upgrade_evolutions: 0,
    upgrade_coins: 1,
    deploy_cost: 1,
    deploy_evolutions: 3,
    deploy_coins: 3,
    build_cost: 2,
    build_evolutions: 2,
    build_coins: 0,
    enlist_cost: 2,
    enlist_evolutions: 1,
    enlist_coins: 2,
};


pub const MECHANICAL: PlayerMat = PlayerMat {
    name: "Mechanical",
    starting_index: 4,
    starting_coins: 6,
    starting_popularity: 3,
    move_secondary: SecondaryAction::Build,
    trade_secondary: SecondaryAction::Upgrade,
    produce_secondary: SecondaryAction::Enlist,
    bolster_secondary: SecondaryAction::Deploy,
    upgrade_cost: 2,
    upgrade_evolutions: 1,
    upgrade_coins: 0,
    deploy_cost: 1,
    deploy_evolutions: 2,
    deploy_coins: 2,
    build_cost: 2,
    build_evolutions: 1,
    build_coins: 2,
    enlist_cost: 2,
    enlist_evolutions: 2,
    enlist_coins: 2,
};


pub const AGRICULTURAL: PlayerMat = PlayerMat {
    name: "Agricultural",
    starting_index: 5,
    starting_coins: 7,
    starting_popularity: 4,
    move_secondary: SecondaryAction::Upgrade,
    trade_secondary: SecondaryAction::Deploy,
    produce_secondary: SecondaryAction::Build,
    bolster_secondary: SecondaryAction::Enlist,
    upgrade_cost: 2,
    upgrade_evolutions: 0,
    upgrade_coins: 1,
    deploy_cost: 2,
    deploy_evolutions: 2,
    deploy_coins: 0,
    build_cost: 2,
    build_evolutions: 2,
    build_coins: 2,
    enlist_cost: 1,
    enlist_evolutions: 2,
    enlist_coins: 3,
};
